name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
      - master
    types:
      # milestone changes
      - milestoned
      - demilestoned
      # label changes for “no milestone”
      - labeled
      - unlabeled
      # initial check
      - opened
      - edited
      - reopened
      # code change (e.g. this workflow)
      - synchronize

env:
  LABELS: ${{ join( github.event.pull_request.labels.*.name, '|' ) }}

jobs:
  check-milestone:
    name: Check Milestone
    runs-on: ubuntu-latest
    steps:
      - name: Check if milestone or “no milestone” label is present
        run: exit ${{ (github.event.pull_request.milestone != null || contains(env.LABELS, 'no milestone')) && '0' || '1'}}
      - uses: actions/checkout@v3
        if: github.event.pull_request.milestone != null
      - name: Check if relevant release notes are set
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: docs/release-notes/${{ github.event.pull_request.milestone.title }}.md
        if: github.event.pull_request.milestone != null
      - name:
        run: exit ${{ steps.verify-changed-files.outputs.files_changed && '0' || '1' }}
        if: github.event.pull_request.milestone != null
