name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
      - master
    types:
      # milestone changes
      - milestoned
      - demilestoned
      # label changes for “no milestone”
      - labeled
      - unlabeled
      # initial check
      - opened
      - edited
      - reopened
      # code change (e.g. this workflow)
      - synchronize

env:
  LABELS: ${{ join( github.event.pull_request.labels.*.name, '|' ) }}

jobs:
  check-milestone:
    name: Check Milestone
    runs-on: ubuntu-latest
    steps:
      - name: Check if milestone or “no milestone” label is present
        uses: flying-sheep/check@v1
        with:
          success: ${{ github.event.pull_request.milestone != null || contains(env.LABELS, 'no milestone') }}
      - uses: actions/checkout@v3
        if: github.event.pull_request.milestone != null
      - name: Find out if relevant release notes are modified
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |  # this is intentionally a string
            relnotes: 'docs/release-notes/${{ github.event.pull_request.milestone.title }}.md'
        if: github.event.pull_request.milestone != null
      - name: Check if relevant release notes are modified
        uses: flying-sheep/check@v1
        with:
          success: ${{ steps.changes.outputs.relnotes }}
        if: github.event.pull_request.milestone != null
